import { RoadmapPageShell } from "../../../components/roadmap/RoadmapPageShell";
import type { ReadinessMetric, RoadmapNode, StageSummary, ProjectTrack } from "../../../components/roadmap/RoadmapPageShell";

const stageSummaries: StageSummary[] = [
  {
    stage: "Beginner",
    duration: "10-14 weeks",
    outcome: "Understand the web, choose a language, use Git, and manage dependencies.",
  },
  {
    stage: "Intermediate",
    duration: "18-24 weeks",
    outcome: "Design APIs, use databases, authenticate users, cache data, and process background work.",
  },
  {
    stage: "Advanced",
    duration: "16-22 weeks",
    outcome: "Design scalable systems, architecture boundaries, observability, security, testing, and DevOps flows.",
  },
  {
    stage: "Expert",
    duration: "18-28 weeks",
    outcome: "Run cloud-native, resilient, cost-aware distributed systems in production.",
  },
];

const roadmapNodes: RoadmapNode[] = [
  {
    id: "internet-fundamentals",
    title: "Internet Fundamentals",
    stage: "Beginner",
    difficulty: "Starter",
    duration: "2 weeks",
    description: "Build the mental model of how requests move from a user device to backend services and back.",
    prerequisites: ["Basic computer literacy"],
    topics: ["How the Web Works", "DNS", "HTTP/HTTPS", "Browsers", "Client vs Server", "TCP/IP Basics"],
    skillsGained: ["Read request/response flows", "Explain DNS resolution", "Understand network layers", "Inspect HTTP traffic"],
    resources: [
      { label: "MDN: How the Web works", href: "https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/How_does_the_Internet_work", category: "Official Docs" },
      { label: "Cloudflare Learning Center", href: "https://www.cloudflare.com/learning/", category: "Official Docs" },
      { label: "HTTP Cats", href: "https://http.cat/", category: "Practice" },
    ],
    practiceExercises: ["Trace a DNS lookup with a command-line tool.", "Inspect request headers in browser devtools.", "Draw a client-server request lifecycle."],
    miniProject: "Create an illustrated web request lifecycle explainer.",
    realWorldApplications: ["Debug slow API responses", "Understand CDN behavior", "Diagnose TLS and DNS issues"],
    quiz: "What happens between entering a URL and receiving HTML from a server?",
  },
  {
    id: "programming-fundamentals",
    title: "Programming Fundamentals",
    stage: "Beginner",
    difficulty: "Starter",
    duration: "6 weeks",
    description: "Learn the programming primitives and problem-solving patterns used in backend services.",
    prerequisites: ["Internet Fundamentals"],
    topics: ["Variables", "Functions", "OOP", "Data Structures", "Algorithms", "Error Handling"],
    skillsGained: ["Write clear functions", "Model data structures", "Handle failures", "Reason about complexity"],
    resources: [
      { label: "freeCodeCamp", href: "https://www.freecodecamp.org/learn/", category: "Practice" },
      { label: "The Algorithms", href: "https://the-algorithms.com/", category: "Community" },
      { label: "Python tutorial", href: "https://docs.python.org/3/tutorial/", category: "Official Docs" },
    ],
    practiceExercises: ["Implement stack, queue, and hash map examples.", "Solve ten basic algorithm problems.", "Write error handling for invalid input."],
    miniProject: "Build a command-line expense tracker.",
    realWorldApplications: ["Input validation", "Business rules", "Service-layer logic"],
    quiz: "When would you use a hash map instead of an array?",
  },
  {
    id: "backend-language-selection",
    title: "Backend Language Selection",
    stage: "Beginner",
    difficulty: "Core",
    duration: "2 weeks",
    description: "Choose a backend language based on ecosystem, team needs, performance, hiring market, and project constraints.",
    prerequisites: ["Programming Fundamentals"],
    topics: ["JavaScript (Node.js)", "TypeScript", "Python", "Java", "Go", "C#", "Rust"],
    skillsGained: ["Compare language tradeoffs", "Choose a runtime", "Evaluate ecosystems", "Read backend project structure"],
    resources: [
      { label: "Node.js docs", href: "https://nodejs.org/en/docs", category: "Official Docs" },
      { label: "Go docs", href: "https://go.dev/doc/", category: "Official Docs" },
      { label: "Rust book", href: "https://doc.rust-lang.org/book/", category: "Official Docs" },
    ],
    practiceExercises: ["Write the same small API handler in two languages.", "Compare package ecosystems.", "Document language tradeoffs for a startup API."],
    miniProject: "Build a hello-world HTTP server in your chosen language.",
    realWorldApplications: ["Tech stack decisions", "Hiring alignment", "Performance planning"],
    quiz: "Why might a team choose Go over Node.js for a backend service?",
  },
  {
    id: "version-control",
    title: "Version Control",
    stage: "Beginner",
    difficulty: "Core",
    duration: "1 week",
    description: "Use Git and GitHub to collaborate safely on backend systems with reviewable change history.",
    prerequisites: ["Programming Fundamentals"],
    topics: ["Git", "GitHub", "Branching", "Pull Requests", "Merge Conflicts"],
    skillsGained: ["Create branches", "Open pull requests", "Resolve conflicts", "Review code"],
    resources: [
      { label: "Git docs", href: "https://git-scm.com/doc", category: "Official Docs" },
      { label: "GitHub Skills", href: "https://skills.github.com/", category: "Practice" },
      { label: "Git roadmap", href: "/roadmaps/git", category: "Community" },
    ],
    practiceExercises: ["Create a feature branch.", "Resolve a merge conflict.", "Review a teammate-style pull request."],
    miniProject: "Publish your first backend API repository with clean commits.",
    realWorldApplications: ["Team collaboration", "Release history", "Rollback planning"],
    quiz: "What is the difference between merge and rebase?",
  },
  {
    id: "package-managers",
    title: "Package Managers",
    stage: "Beginner",
    difficulty: "Core",
    duration: "1 week",
    description: "Manage dependencies, scripts, lockfiles, and build tools across backend language ecosystems.",
    prerequisites: ["Backend Language Selection", "Version Control"],
    topics: ["npm", "pnpm", "yarn", "pip", "Maven", "Gradle"],
    skillsGained: ["Install dependencies", "Use lockfiles", "Write scripts", "Audit packages"],
    resources: [
      { label: "npm docs", href: "https://docs.npmjs.com/", category: "Official Docs" },
      { label: "pip docs", href: "https://pip.pypa.io/en/stable/", category: "Official Docs" },
      { label: "Maven docs", href: "https://maven.apache.org/guides/", category: "Official Docs" },
    ],
    practiceExercises: ["Create dev/build/test scripts.", "Explain semantic version ranges.", "Compare npm, pnpm, pip, and Maven workflows."],
    miniProject: "Create a backend starter package with scripts and dependency documentation.",
    realWorldApplications: ["Dependency hygiene", "CI builds", "Supply-chain safety"],
    quiz: "Why should production services commit lockfiles?",
  },
  {
    id: "databases",
    title: "Databases",
    stage: "Intermediate",
    difficulty: "Applied",
    duration: "6 weeks",
    description: "Design relational databases, write efficient queries, and optimize data access for production workloads.",
    prerequisites: ["Programming Fundamentals"],
    topics: ["SQL", "PostgreSQL", "MySQL", "Database Design", "Normalization", "Indexing", "Query Optimization"],
    skillsGained: ["Model relational data", "Write SQL joins", "Design indexes", "Analyze query plans"],
    resources: [
      { label: "PostgreSQL docs", href: "https://www.postgresql.org/docs/", category: "Official Docs" },
      { label: "SQLBolt", href: "https://sqlbolt.com/", category: "Practice" },
      { label: "Use The Index, Luke", href: "https://use-the-index-luke.com/", category: "Community" },
    ],
    practiceExercises: ["Design normalized tables for a blog.", "Write joins and aggregations.", "Use EXPLAIN on a slow query."],
    miniProject: "Build a notes API backed by PostgreSQL.",
    realWorldApplications: ["User data storage", "Analytics queries", "Transactional systems"],
    quiz: "How does an index speed up reads and slow down writes?",
  },
  {
    id: "nosql-databases",
    title: "NoSQL Databases",
    stage: "Intermediate",
    difficulty: "Applied",
    duration: "3 weeks",
    description: "Understand document, key-value, wide-column, and managed NoSQL databases for flexible or high-scale workloads.",
    prerequisites: ["Databases"],
    topics: ["MongoDB", "Redis", "Cassandra", "DynamoDB"],
    skillsGained: ["Choose NoSQL data models", "Use document collections", "Use key-value stores", "Understand partitioning"],
    resources: [
      { label: "MongoDB docs", href: "https://www.mongodb.com/docs/", category: "Official Docs" },
      { label: "Redis docs", href: "https://redis.io/docs/latest/", category: "Official Docs" },
      { label: "DynamoDB guide", href: "https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Introduction.html", category: "Official Docs" },
    ],
    practiceExercises: ["Design a MongoDB schema.", "Use Redis for hot keys.", "Compare relational vs document modeling."],
    miniProject: "Build a product catalog with MongoDB and Redis caching.",
    realWorldApplications: ["Session stores", "Catalog data", "High-throughput key-value access"],
    quiz: "When is denormalization a good NoSQL tradeoff?",
  },
  {
    id: "api-development",
    title: "API Development",
    stage: "Intermediate",
    difficulty: "Applied",
    duration: "5 weeks",
    description: "Design robust APIs with predictable contracts, documentation, versioning, validation, and error semantics.",
    prerequisites: ["Databases", "Backend Language Selection"],
    topics: ["REST", "GraphQL", "gRPC", "API Versioning", "API Documentation"],
    skillsGained: ["Design REST resources", "Write OpenAPI docs", "Validate payloads", "Version APIs"],
    resources: [
      { label: "OpenAPI specification", href: "https://spec.openapis.org/oas/latest.html", category: "Official Docs" },
      { label: "GraphQL Learn", href: "https://graphql.org/learn/", category: "Official Docs" },
      { label: "gRPC docs", href: "https://grpc.io/docs/", category: "Official Docs" },
    ],
    practiceExercises: ["Design endpoints for a notes app.", "Write OpenAPI documentation.", "Add validation and structured errors."],
    miniProject: "Build a versioned REST API with docs and validation.",
    realWorldApplications: ["Public APIs", "Internal services", "Mobile app backends"],
    quiz: "What makes an API backwards compatible?",
  },
  {
    id: "authentication-authorization",
    title: "Authentication & Authorization",
    stage: "Intermediate",
    difficulty: "Advanced",
    duration: "4 weeks",
    description: "Secure identities, sessions, tokens, roles, and sensitive user workflows.",
    prerequisites: ["API Development", "Security basics"],
    topics: ["Sessions", "Cookies", "JWT", "OAuth", "RBAC", "MFA"],
    skillsGained: ["Implement login flows", "Protect routes", "Model roles", "Handle token lifecycles"],
    resources: [
      { label: "Auth0 identity docs", href: "https://auth0.com/docs", category: "Official Docs" },
      { label: "OWASP Authentication Cheat Sheet", href: "https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html", category: "Official Docs" },
      { label: "OAuth 2.0", href: "https://oauth.net/2/", category: "Official Docs" },
    ],
    practiceExercises: ["Create signup/login/logout.", "Add role-protected endpoints.", "Implement refresh-token rotation notes."],
    miniProject: "Build a secure authentication system with RBAC.",
    realWorldApplications: ["SaaS accounts", "Admin panels", "Enterprise access control"],
    quiz: "What is the difference between authentication and authorization?",
  },
  {
    id: "backend-frameworks",
    title: "Backend Frameworks",
    stage: "Intermediate",
    difficulty: "Applied",
    duration: "5 weeks",
    description: "Use backend frameworks to structure routing, middleware, validation, controllers, services, and dependency boundaries.",
    prerequisites: ["API Development", "Backend Language Selection"],
    topics: ["Express.js", "NestJS", "Django", "Spring Boot", "FastAPI", "Gin"],
    skillsGained: ["Use middleware", "Create controllers", "Structure services", "Configure framework conventions"],
    resources: [
      { label: "Express docs", href: "https://expressjs.com/", category: "Official Docs" },
      { label: "NestJS docs", href: "https://docs.nestjs.com/", category: "Official Docs" },
      { label: "FastAPI docs", href: "https://fastapi.tiangolo.com/", category: "Official Docs" },
    ],
    practiceExercises: ["Build CRUD routes.", "Add middleware and validation.", "Separate controller and service logic."],
    miniProject: "Build a blog backend with posts, users, comments, and admin moderation.",
    realWorldApplications: ["Production web APIs", "Admin systems", "Backend services"],
    quiz: "Why should business logic avoid living directly in route handlers?",
  },
  {
    id: "caching",
    title: "Caching",
    stage: "Intermediate",
    difficulty: "Applied",
    duration: "2 weeks",
    description: "Reduce latency and backend load with Redis, CDNs, cache keys, invalidation, and cache-aside patterns.",
    prerequisites: ["Databases", "API Development"],
    topics: ["Redis", "CDN", "Cache Strategies"],
    skillsGained: ["Design cache keys", "Use TTLs", "Avoid stale data bugs", "Measure cache hit ratio"],
    resources: [
      { label: "Redis docs", href: "https://redis.io/docs/latest/", category: "Official Docs" },
      { label: "Cloudflare CDN learning", href: "https://www.cloudflare.com/learning/cdn/what-is-a-cdn/", category: "Official Docs" },
      { label: "AWS caching overview", href: "https://aws.amazon.com/caching/", category: "Official Docs" },
    ],
    practiceExercises: ["Cache expensive read queries.", "Add TTL and invalidation rules.", "Measure before and after response time."],
    miniProject: "Add Redis caching to an e-commerce product API.",
    realWorldApplications: ["Fast product pages", "Rate-limited APIs", "Read-heavy dashboards"],
    quiz: "What can go wrong with cache invalidation?",
  },
  {
    id: "message-queues",
    title: "Message Queues",
    stage: "Intermediate",
    difficulty: "Advanced",
    duration: "3 weeks",
    description: "Process background work and asynchronous communication with durable queues and event streams.",
    prerequisites: ["API Development", "Caching"],
    topics: ["RabbitMQ", "Kafka", "SQS"],
    skillsGained: ["Publish messages", "Consume jobs", "Retry safely", "Understand ordering and delivery guarantees"],
    resources: [
      { label: "RabbitMQ tutorials", href: "https://www.rabbitmq.com/tutorials", category: "Official Docs" },
      { label: "Kafka docs", href: "https://kafka.apache.org/documentation/", category: "Official Docs" },
      { label: "Amazon SQS docs", href: "https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/welcome.html", category: "Official Docs" },
    ],
    practiceExercises: ["Create a background email job.", "Implement retries and dead-letter notes.", "Compare queue vs event stream."],
    miniProject: "Build an async notification worker for a blog backend.",
    realWorldApplications: ["Email delivery", "Order processing", "Event pipelines"],
    quiz: "Why should queue consumers be idempotent?",
  },
  {
    id: "file-storage",
    title: "File Storage",
    stage: "Intermediate",
    difficulty: "Applied",
    duration: "2 weeks",
    description: "Handle uploads, file validation, object storage, signed URLs, metadata, and safe delivery.",
    prerequisites: ["API Development", "Authentication & Authorization"],
    topics: ["Local Storage", "AWS S3", "Cloud Storage", "File Upload Systems"],
    skillsGained: ["Validate uploads", "Use object storage", "Generate signed URLs", "Store metadata"],
    resources: [
      { label: "Amazon S3 docs", href: "https://docs.aws.amazon.com/s3/", category: "Official Docs" },
      { label: "Google Cloud Storage docs", href: "https://cloud.google.com/storage/docs", category: "Official Docs" },
      { label: "Multer docs", href: "https://github.com/expressjs/multer", category: "Community" },
    ],
    practiceExercises: ["Upload images safely.", "Generate signed download URLs.", "Reject invalid file types and sizes."],
    miniProject: "Build a file storage service with metadata and access control.",
    realWorldApplications: ["Profile images", "Document storage", "Media delivery"],
    quiz: "Why should user uploads not be served directly from application servers?",
  },
  {
    id: "system-design",
    title: "System Design",
    stage: "Advanced",
    difficulty: "Advanced",
    duration: "6 weeks",
    description: "Design services that scale horizontally, tolerate failures, and meet latency and throughput requirements.",
    prerequisites: ["Databases", "API Development", "Caching"],
    topics: ["Scalability", "Load Balancing", "Horizontal Scaling", "Vertical Scaling", "Distributed Systems"],
    skillsGained: ["Estimate capacity", "Design load-balanced systems", "Identify bottlenecks", "Choose scaling strategies"],
    resources: [
      { label: "System Design Primer", href: "https://github.com/donnemartin/system-design-primer", category: "Community" },
      { label: "AWS Well-Architected", href: "https://docs.aws.amazon.com/wellarchitected/latest/framework/welcome.html", category: "Official Docs" },
      { label: "Google SRE books", href: "https://sre.google/books/", category: "Official Docs" },
    ],
    practiceExercises: ["Design a URL shortener.", "Estimate traffic and storage.", "Identify single points of failure."],
    miniProject: "Build a scalable URL shortener with analytics.",
    realWorldApplications: ["Interview design rounds", "Capacity planning", "Architecture reviews"],
    quiz: "When would horizontal scaling be better than vertical scaling?",
  },
  {
    id: "architecture-patterns",
    title: "Architecture Patterns",
    stage: "Advanced",
    difficulty: "Advanced",
    duration: "4 weeks",
    description: "Choose structural patterns that keep backend systems maintainable as teams, features, and traffic grow.",
    prerequisites: ["Backend Frameworks", "System Design"],
    topics: ["Monolith", "Microservices", "Event Driven Architecture", "Clean Architecture", "Hexagonal Architecture"],
    skillsGained: ["Separate domain logic", "Model boundaries", "Choose monolith vs microservices", "Use ports and adapters"],
    resources: [
      { label: "Martin Fowler architecture", href: "https://martinfowler.com/architecture/", category: "Community" },
      { label: "Microservices guide", href: "https://microservices.io/", category: "Community" },
      { label: "AWS event-driven architecture", href: "https://aws.amazon.com/event-driven-architecture/", category: "Official Docs" },
    ],
    practiceExercises: ["Refactor routes into domain services.", "Draw service boundaries.", "Compare event-driven and request-driven flows."],
    miniProject: "Build a chat backend with separated domain, transport, and persistence layers.",
    realWorldApplications: ["SaaS backend structure", "Team ownership", "Legacy modernization"],
    quiz: "Why are microservices expensive before a team has clear domain boundaries?",
  },
  {
    id: "observability",
    title: "Observability",
    stage: "Advanced",
    difficulty: "Advanced",
    duration: "3 weeks",
    description: "Make production systems understandable with logs, metrics, traces, dashboards, and alerting.",
    prerequisites: ["System Design", "Backend Frameworks"],
    topics: ["Logging", "Monitoring", "Metrics", "Tracing"],
    skillsGained: ["Write structured logs", "Create metrics", "Trace requests", "Design alerts"],
    resources: [
      { label: "OpenTelemetry docs", href: "https://opentelemetry.io/docs/", category: "Official Docs" },
      { label: "Prometheus docs", href: "https://prometheus.io/docs/introduction/overview/", category: "Official Docs" },
      { label: "Grafana docs", href: "https://grafana.com/docs/", category: "Official Docs" },
    ],
    practiceExercises: ["Add request IDs to logs.", "Create latency and error metrics.", "Trace one request through multiple services."],
    miniProject: "Add observability to a file storage service.",
    realWorldApplications: ["Incident response", "Performance debugging", "SLO tracking"],
    quiz: "What is the difference between metrics and traces?",
  },
  {
    id: "security",
    title: "Security",
    stage: "Advanced",
    difficulty: "Expert",
    duration: "5 weeks",
    description: "Protect backend systems against common application, API, and infrastructure risks.",
    prerequisites: ["Authentication & Authorization", "API Development"],
    topics: ["OWASP Top 10", "SQL Injection", "XSS", "CSRF", "Rate Limiting", "Security Headers"],
    skillsGained: ["Threat model APIs", "Prevent injection", "Use secure headers", "Rate-limit abuse"],
    resources: [
      { label: "OWASP Top 10", href: "https://owasp.org/www-project-top-ten/", category: "Official Docs" },
      { label: "OWASP API Security", href: "https://owasp.org/www-project-api-security/", category: "Official Docs" },
      { label: "PortSwigger Academy", href: "https://portswigger.net/web-security", category: "Practice" },
    ],
    practiceExercises: ["Fix SQL injection in a sample endpoint.", "Add rate limits.", "Create a security checklist for releases."],
    miniProject: "Harden an authentication API against common attacks.",
    realWorldApplications: ["Compliance", "Abuse prevention", "Data protection"],
    quiz: "How do parameterized queries prevent SQL injection?",
  },
  {
    id: "testing",
    title: "Testing",
    stage: "Advanced",
    difficulty: "Advanced",
    duration: "4 weeks",
    description: "Verify backend behavior with fast unit tests, realistic integration tests, E2E tests, and load tests.",
    prerequisites: ["Backend Frameworks", "Databases"],
    topics: ["Unit Testing", "Integration Testing", "End-to-End Testing", "Load Testing"],
    skillsGained: ["Test services", "Mock dependencies", "Spin up test databases", "Measure load behavior"],
    resources: [
      { label: "Jest docs", href: "https://jestjs.io/docs/getting-started", category: "Official Docs" },
      { label: "pytest docs", href: "https://docs.pytest.org/", category: "Official Docs" },
      { label: "k6 docs", href: "https://k6.io/docs/", category: "Official Docs" },
    ],
    practiceExercises: ["Write unit tests for services.", "Run integration tests against a test database.", "Load test one endpoint."],
    miniProject: "Create a tested e-commerce API with payment-flow mocks.",
    realWorldApplications: ["Release confidence", "Regression prevention", "Performance validation"],
    quiz: "When is an integration test more valuable than a unit test?",
  },
  {
    id: "devops-fundamentals",
    title: "DevOps Fundamentals",
    stage: "Advanced",
    difficulty: "Advanced",
    duration: "5 weeks",
    description: "Operate backend services with Linux, shell scripting, CI/CD, Docker, and repeatable release workflows.",
    prerequisites: ["Testing", "Version Control"],
    topics: ["Linux", "Bash", "CI/CD", "GitHub Actions", "Docker"],
    skillsGained: ["Use Linux servers", "Write Bash scripts", "Create CI workflows", "Containerize services"],
    resources: [
      { label: "Docker docs", href: "https://docs.docker.com/", category: "Official Docs" },
      { label: "GitHub Actions docs", href: "https://docs.github.com/en/actions", category: "Official Docs" },
      { label: "Linux Journey", href: "https://linuxjourney.com/", category: "Practice" },
    ],
    practiceExercises: ["Write a Dockerfile.", "Create a GitHub Actions build pipeline.", "Use Bash to automate local setup."],
    miniProject: "Containerize and deploy a tested backend API.",
    realWorldApplications: ["CI/CD", "Deployment automation", "Environment parity"],
    quiz: "What problem does Docker solve for backend teams?",
  },
  {
    id: "cloud-platforms",
    title: "Cloud Platforms",
    stage: "Expert",
    difficulty: "Advanced",
    duration: "6 weeks",
    description: "Deploy and operate backend workloads across cloud compute, networking, databases, storage, and managed services.",
    prerequisites: ["DevOps Fundamentals", "System Design"],
    topics: ["AWS", "Azure", "Google Cloud"],
    skillsGained: ["Choose cloud services", "Configure managed databases", "Understand IAM", "Design cloud deployments"],
    resources: [
      { label: "AWS docs", href: "https://docs.aws.amazon.com/", category: "Official Docs" },
      { label: "Azure docs", href: "https://learn.microsoft.com/en-us/azure/", category: "Official Docs" },
      { label: "Google Cloud docs", href: "https://cloud.google.com/docs", category: "Official Docs" },
    ],
    practiceExercises: ["Map app components to cloud services.", "Create a managed database.", "Document IAM boundaries."],
    miniProject: "Deploy a backend API with managed database and object storage.",
    realWorldApplications: ["Production hosting", "Managed infrastructure", "Cloud migration"],
    quiz: "Why is IAM a core backend production skill?",
  },
  {
    id: "containerization-orchestration",
    title: "Containerization & Orchestration",
    stage: "Expert",
    difficulty: "Expert",
    duration: "5 weeks",
    description: "Run containerized services reliably with Docker, Kubernetes, Helm, health checks, and rollout strategies.",
    prerequisites: ["DevOps Fundamentals", "Cloud Platforms"],
    topics: ["Docker", "Kubernetes", "Helm"],
    skillsGained: ["Build images", "Deploy pods", "Configure services", "Use Helm charts", "Manage rollouts"],
    resources: [
      { label: "Kubernetes docs", href: "https://kubernetes.io/docs/home/", category: "Official Docs" },
      { label: "Helm docs", href: "https://helm.sh/docs/", category: "Official Docs" },
      { label: "Play with Kubernetes", href: "https://labs.play-with-k8s.com/", category: "Practice" },
    ],
    practiceExercises: ["Deploy a container to Kubernetes.", "Add readiness and liveness probes.", "Package a service with Helm."],
    miniProject: "Run a multi-service backend on Kubernetes.",
    realWorldApplications: ["Microservice platforms", "Autoscaling", "Cloud-native operations"],
    quiz: "What is the difference between a deployment and a service in Kubernetes?",
  },
  {
    id: "infrastructure-as-code",
    title: "Infrastructure as Code",
    stage: "Expert",
    difficulty: "Expert",
    duration: "4 weeks",
    description: "Define infrastructure safely and repeatably using declarative or programmatic tooling.",
    prerequisites: ["Cloud Platforms", "DevOps Fundamentals"],
    topics: ["Terraform", "Pulumi"],
    skillsGained: ["Write IaC modules", "Plan changes", "Manage state", "Review infrastructure diffs"],
    resources: [
      { label: "Terraform docs", href: "https://developer.hashicorp.com/terraform/docs", category: "Official Docs" },
      { label: "Pulumi docs", href: "https://www.pulumi.com/docs/", category: "Official Docs" },
      { label: "Terraform AWS tutorials", href: "https://developer.hashicorp.com/terraform/tutorials/aws-get-started", category: "Practice" },
    ],
    practiceExercises: ["Provision a database with IaC.", "Review a plan output.", "Create reusable environment variables and modules."],
    miniProject: "Provision a cloud backend environment using Terraform.",
    realWorldApplications: ["Repeatable environments", "Compliance review", "Infrastructure versioning"],
    quiz: "Why is Terraform state sensitive?",
  },
  {
    id: "advanced-scalability",
    title: "Advanced Scalability",
    stage: "Expert",
    difficulty: "Expert",
    duration: "6 weeks",
    description: "Handle large-scale data and traffic with sharding, replication, CQRS, event sourcing, and asynchronous architecture.",
    prerequisites: ["System Design", "Architecture Patterns", "Cloud Platforms"],
    topics: ["Sharding", "Replication", "Event Sourcing", "CQRS"],
    skillsGained: ["Partition data", "Design replication", "Separate read/write models", "Use event histories"],
    resources: [
      { label: "Designing Data-Intensive Applications notes", href: "https://dataintensive.net/", category: "Community" },
      { label: "Azure CQRS pattern", href: "https://learn.microsoft.com/en-us/azure/architecture/patterns/cqrs", category: "Official Docs" },
      { label: "AWS event sourcing", href: "https://docs.aws.amazon.com/prescriptive-guidance/latest/cloud-design-patterns/event-sourcing.html", category: "Official Docs" },
    ],
    practiceExercises: ["Design database shards for tenant data.", "Create read/write model diagrams.", "Model event history for an order system."],
    miniProject: "Design a scalable SaaS backend with CQRS and event streams.",
    realWorldApplications: ["Large SaaS systems", "Analytics-heavy services", "Event-driven platforms"],
    quiz: "What tradeoffs does sharding introduce?",
  },
  {
    id: "production-engineering",
    title: "Production Engineering",
    stage: "Expert",
    difficulty: "Expert",
    duration: "6 weeks",
    description: "Operate high-availability systems with reliability targets, disaster recovery, incident response, and cost controls.",
    prerequisites: ["Observability", "Advanced Scalability", "Infrastructure as Code"],
    topics: ["Reliability", "High Availability", "Disaster Recovery", "Cost Optimization"],
    skillsGained: ["Define SLOs", "Plan failover", "Run postmortems", "Optimize cloud spend"],
    resources: [
      { label: "Google SRE books", href: "https://sre.google/books/", category: "Official Docs" },
      { label: "AWS reliability pillar", href: "https://docs.aws.amazon.com/wellarchitected/latest/reliability-pillar/welcome.html", category: "Official Docs" },
      { label: "FinOps Foundation", href: "https://www.finops.org/introduction/what-is-finops/", category: "Community" },
    ],
    practiceExercises: ["Write an incident runbook.", "Create an SLO and error budget.", "Estimate monthly cloud cost for a service."],
    miniProject: "Design a highly available backend with disaster recovery and cost controls.",
    realWorldApplications: ["On-call readiness", "Enterprise SLAs", "Production reliability"],
    quiz: "What is the difference between availability and reliability?",
  },
];

const projectTracks: ProjectTrack[] = [
  { stage: "Beginner", projects: ["Calculator API", "Notes API"] },
  { stage: "Intermediate", projects: ["Authentication System", "Blog Backend", "E-commerce API"] },
  { stage: "Advanced", projects: ["URL Shortener", "Chat Application Backend", "File Storage Service"] },
  { stage: "Expert", projects: ["Distributed Microservices Platform", "Netflix-style Backend Architecture", "Scalable SaaS Backend"] },
];

const missingTopics: string[] = [
  "Domain-driven design",
  "API gateways",
  "Service discovery",
  "Secrets management",
  "Database migrations",
  "Backup strategy",
  "Feature flags",
  "Blue-green deployments",
  "Contract testing",
  "Data privacy and compliance",
];

const resourceCategories: string[] = ["Official Docs", "Video", "Practice", "Community"];

const readinessMetrics: ReadinessMetric[] = [
  { label: "API readiness", icon: "server", topicTitles: ["API Development", "Backend Frameworks", "Authentication & Authorization"] },
  { label: "Database readiness", icon: "layers", topicTitles: ["Databases", "NoSQL Databases", "Caching"] },
  { label: "Production readiness", icon: "shield", topicTitles: ["System Design", "Security", "DevOps Fundamentals", "Cloud Platforms"] },
];

export default function BackendDeveloperRoadmap() {
  return (
    <RoadmapPageShell
      storageKey="demontech-backend-roadmap"
      breadcrumb="Backend Developer"
      eyebrow="Production Backend Engineering Path"
      title="Backend Developer Roadmap"
      description="A complete server-side learning journey from internet fundamentals to distributed systems, cloud platforms, security, observability, and production engineering."
      stats={[["24", "Roadmap nodes", "layers"], ["46-68 weeks", "Total duration", "clock"], ["96+", "Skills tracked", "badge"], ["12", "Project builds", "target"]]}
      architectureLabel="Level Architecture"
      projectIntro="Every level ends with shippable backend systems that combine APIs, persistence, auth, reliability, and deployment skills."
      journeyTitle="Vertical Backend Journey"
      journeyDescription="Expand each node for prerequisites, resources, practice exercises, mini projects, real-world usage, quiz prompts, bookmarks, and notes."
      resourceTitle="Backend Resource Matrix"
      progressTitle="Backend Progress"
      readinessTitle="Backend Readiness"
      missingTitle="Missing Backend Topics Added"
      estimatedTime="46-68w"
      miniProjectLabel="Mini Project"
      stageSummaries={stageSummaries}
      roadmapNodes={roadmapNodes}
      projectTracks={projectTracks}
      resourceCategories={resourceCategories}
      achievementBadges={["API Architect", "Database Designer", "Security Defender", "Cloud Operator"]}
      missingTopics={missingTopics}
      readinessMetrics={readinessMetrics}
    />
  );
}
